version: "3.8"
services:
    db:
        container_name: postgresql_container
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test123
    web:
        container_name: django_container
        build: .
        volumes:
            - ./:/code
        ports:
            - 8000:8000
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db
