# Generated by Django 3.1.2 on 2021-02-12 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=283)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('pgmming', 'Programming'), ('phy', 'Physics'), ('maths', 'Maths'), ('chemistry', 'English')], max_length=12, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
