# Generated by Django 3.1.2 on 2021-02-12 18:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tech', 'Tech'), ('edu', 'Education'), ('gam', 'Gaming'), ('sci', 'Science'), ('rand', 'Random'), ('politics', 'Politics'), ('pets', 'Pets'), ('arts', 'Arts'), ('vid', 'Video'), ('social', 'Social'), ('hobbies', 'Hobbies')], max_length=12, null=True),
        ),
    ]
