# Generated by Django 3.1.2 on 2021-02-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0005_auto_20210212_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='threadreply',
            options={'ordering': ['-upvotes', '-hearts']},
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='threadreply',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
