# Generated by Django 3.1.2 on 2021-02-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0006_auto_20210212_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadreply',
            options={'ordering': ['-upvotes', '-hearts'], 'verbose_name_plural': 'ThreadReplies'},
        ),
    ]
