# Generated by Django 3.1.2 on 2021-02-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0007_auto_20210212_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'ForumThreads'},
        ),
    ]
