# Generated by Django 3.1.2 on 2021-02-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0010_threadreply_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadreply',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='threadreply',
            name='hidden',
        ),
    ]
