# Generated by Django 3.1.2 on 2021-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0011_auto_20210213_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadreply',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
