# Generated by Django 3.1.2 on 2021-02-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0012_threadreply_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadreply',
            old_name='closed',
            new_name='hidden',
        ),
    ]
