# Generated by Django 3.1.2 on 2021-02-13 04:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0013_auto_20210213_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('arts', 'Arts'), ('edu', 'Education'), ('entertain', 'Entertainment'), ('gam', 'Gaming'), ('hobbies', 'Hobbies'), ('pets', 'Pets'), ('photo', 'Photography'), ('politics', 'Politics'), ('rand', 'Random'), ('sci', 'Science'), ('social', 'Social'), ('tech', 'Tech'), ('travel', 'Travel'), ('vid', 'Video')], max_length=24, null=True),
        ),
    ]
