# Generated by Django 3.1.2 on 2021-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0015_auto_20210213_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
