# Generated by Django 3.1.2 on 2021-02-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0016_auto_20210213_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'ForumThreads'},
        ),
        migrations.AlterModelOptions(
            name='threadreply',
            options={'ordering': ('-created_on', '-upvotes', '-hearts'), 'verbose_name_plural': 'ThreadReplies'},
        ),
    ]
