# Generated by Django 3.1.2 on 2021-02-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0018_baseconfig_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseconfig',
            options={'verbose_name_plural': 'BaseConfig'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'SocialMedias'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='css_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(default='hello', max_length=283),
            preserve_default=False,
        ),
    ]
