# Generated by Django 3.1.2 on 2021-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0019_auto_20210213_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='baseConfig',
        ),
        migrations.AddField(
            model_name='baseconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='baseconfig',
            name='title',
            field=models.CharField(help_text='Only One Instance Is Allowed', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='css_class',
            field=models.CharField(blank=True, help_text='FontAwesome. Example: facebook-square', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(help_text='Example: Facebook,Instagram', max_length=12),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(help_text='Example: https://www.facebook.com/Shuvraj.lama7', max_length=283),
        ),
    ]
