# Generated by Django 3.1.2 on 2021-02-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0020_auto_20210213_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepage',
            options={'verbose_name_plural': 'BasePages'},
        ),
    ]
