# Generated by Django 3.1.2 on 2021-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0021_auto_20210213_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
