# Generated by Django 3.1.2 on 2021-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0022_basetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetag',
            options={'verbose_name_plural': 'BaseTags'},
        ),
        migrations.AddField(
            model_name='baseconfig',
            name='header',
            field=models.CharField(default='askbuddie', max_length=15),
            preserve_default=False,
        ),
    ]
