# Generated by Django 3.1.2 on 2021-02-13 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbuddie', '0023_auto_20210213_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('arts', 'Arts'), ('edu', 'Education'), ('entertain', 'Entertainment'), ('gam', 'Gaming'), ('hobbies', 'Hobbies'), ('pets', 'Pets'), ('photo', 'Photography'), ('politics', 'Politics'), ('rand', 'Random'), ('sci', 'Science'), ('social', 'Social'), ('tech', 'Tech'), ('travel', 'Travel'), ('vid', 'Video'), ('nature', 'Nature')], max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='profile')),
                ('socialHandle', models.URLField(max_length=283)),
                ('UserProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
