# Generated by Django 3.1.2 on 2021-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0024_auto_20210213_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='socialHandle',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
    ]
