# Generated by Django 3.1.2 on 2021-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0026_auto_20210214_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon'),
        ),
    ]
