# Generated by Django 3.1.2 on 2021-02-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0027_baseconfig_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='baseConfig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_page', to='askbuddie.baseconfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basetag',
            name='baseConfig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_tag', to='askbuddie.baseconfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='baseConfig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_social', to='askbuddie.baseconfig'),
            preserve_default=False,
        ),
    ]
