# Generated by Django 3.1.2 on 2021-02-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbuddie', '0028_auto_20210214_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfig',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
