# Generated by Django 3.1.2 on 2021-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0030_forumthread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='topic',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
