# Generated by Django 3.1.2 on 2021-02-17 07:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0033_auto_20210217_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('arts', 'Arts'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('gaming', 'Gaming'), ('hobbies', 'Hobbies'), ('pets', 'Pets'), ('photography', 'Photography'), ('politics', 'Politics'), ('random', 'Random'), ('science', 'Science'), ('social', 'Social'), ('tech', 'Tech'), ('travel', 'Travel'), ('video', 'Video'), ('nature', 'Nature')], max_length=34, null=True),
        ),
    ]
