# Generated by Django 3.1.2 on 2021-02-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0038_auto_20210219_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadreply',
            options={'ordering': ('-created_on', '-upvotes', '-hearts'), 'verbose_name_plural': 'ThreadReplies'},
        ),
    ]
