# Generated by Django 3.1.2 on 2021-02-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0039_auto_20210219_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='threadreply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
