# Generated by Django 3.1.2 on 2021-02-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0040_auto_20210220_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadreply',
            options={'ordering': ('-upvotes', '-hearts', '-created_on'), 'verbose_name_plural': 'ThreadReplies'},
        ),
    ]
