# Generated by Django 3.1.2 on 2021-02-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0041_auto_20210220_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
