# Generated by Django 3.1.2 on 2021-02-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0042_auto_20210220_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(help_text='Example: Facebook,Instagram', max_length=12, unique=True),
        ),
    ]
