# Generated by Django 3.1.2 on 2021-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0043_auto_20210220_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
