# Generated by Django 3.1.2 on 2021-02-20 06:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0044_basepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadreply',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
