# Generated by Django 3.1.2 on 2021-02-20 06:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0045_auto_20210220_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
