# Generated by Django 3.1.2 on 2021-02-20 13:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0046_auto_20210220_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadreply',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
