# Generated by Django 3.1.2 on 2021-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0049_auto_20210220_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
