# Generated by Django 3.1.2 on 2021-02-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0050_userprofile_send_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='default.png', null=True, upload_to='profile'),
        ),
    ]
