# Generated by Django 3.1.2 on 2021-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0051_auto_20210225_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='profile/default.png', null=True, upload_to='profile'),
        ),
        migrations.CreateModel(
            name='ThreadTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('forumThread', models.ManyToManyField(related_name='forum_tag', to='askbuddie.ForumThread')),
            ],
        ),
    ]
