# Generated by Django 3.1.2 on 2021-02-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0052_auto_20210226_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadtag',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
