# Generated by Django 3.1.2 on 2021-02-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0053_auto_20210226_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
