# Generated by Django 3.1.2 on 2021-02-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0054_auto_20210226_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadtag',
            name='forumThread',
        ),
    ]
