# Generated by Django 3.1.2 on 2021-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0055_remove_threadtag_forumthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadtag',
            name='forumThread',
            field=models.ManyToManyField(related_name='forum_tag', to='askbuddie.ForumThread'),
        ),
    ]
