# Generated by Django 3.1.2 on 2021-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0057_auto_20210226_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtag',
            name='forumThread',
            field=models.ManyToManyField(related_name='forum_tag', related_query_name='withTag', to='askbuddie.ForumThread'),
        ),
    ]
