# Generated by Django 3.1.2 on 2021-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0058_auto_20210227_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfig',
            name='analytics',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
