# Generated by Django 3.1.2 on 2021-03-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0059_baseconfig_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True),
        ),
    ]
