# Generated by Django 3.1.2 on 2021-03-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0060_auto_20210302_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtag',
            name='tag',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
