# Generated by Django 3.1.2 on 2021-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0062_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
