# Generated by Django 3.1.2 on 2021-04-28 08:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('askbuddie', '0063_auto_20210303_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='fb_post_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('arts', 'Arts'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('gaming', 'Gaming'), ('hobbies', 'Hobbies'), ('maths', 'Maths'), ('pets', 'Pets'), ('photography', 'Photography'), ('programming', 'Programming'), ('politics', 'Politics'), ('random', 'Random'), ('science', 'Science'), ('social', 'Social'), ('tech', 'Tech'), ('travel', 'Travel'), ('video', 'Video'), ('nature', 'Nature')], max_length=34, null=True),
        ),
    ]
